// Change detection — what moved since last time, at two levels.
//
// Token level: what a designer changed in Figma. This is the output a
// developer reads to answer "what do I have to update?", and it is the whole
// point of committing tokens.json rather than only the generated code.
//
// File level: which generated files really changed. Every generated header
// embeds an extraction timestamp, so a byte comparison marks every file as
// changed after any re-extraction. Stripping the header first is what turns
// "8 files updated" into the truth — usually one.

import { EXPORTED_GROUPS } from './dtcg.mjs';

/** Compares two token values structurally; typography values are objects and shadows are arrays. */
function sameValue(a, b) {
  return JSON.stringify(a) === JSON.stringify(b);
}

/**
 * Structured diff between two token sets.
 *
 * Compares `$value` AND every entry in `$modes`, so a change that only lands
 * in dark mode is as visible as one in the default mode. Comparing `$value`
 * alone silently reported "no changes" for a dark-only edit, which is exactly
 * the case someone runs this to catch.
 *
 * @returns {{entries: Array<{kind, group, name, mode, before, after}>, counts: {added, removed, changed}}}
 */
export function diffTokenSets(baseline, current) {
  const entries = [];

  for (const group of EXPORTED_GROUPS) {
    const before = baseline[group] ?? {};
    const after = current[group] ?? {};

    for (const [name, token] of Object.entries(after)) {
      if (!(name in before)) {
        entries.push({ kind: 'added', group, name, mode: null, before: undefined, after: token.$value });
        continue;
      }
      if (!sameValue(before[name].$value, token.$value)) {
        entries.push({ kind: 'changed', group, name, mode: null, before: before[name].$value, after: token.$value });
      }
      // Per-mode values. A mode appearing or disappearing is a change too:
      // it means the token stopped (or started) varying by theme.
      const modeNames = new Set([...Object.keys(before[name].$modes ?? {}), ...Object.keys(token.$modes ?? {})]);
      for (const mode of modeNames) {
        const modeBefore = before[name].$modes?.[mode];
        const modeAfter = token.$modes?.[mode];
        if (sameValue(modeBefore, modeAfter)) continue;
        if (modeBefore === undefined) {
          entries.push({ kind: 'added', group, name, mode, before: undefined, after: modeAfter });
        } else if (modeAfter === undefined) {
          entries.push({ kind: 'removed', group, name, mode, before: modeBefore, after: undefined });
        } else {
          entries.push({ kind: 'changed', group, name, mode, before: modeBefore, after: modeAfter });
        }
      }
    }

    for (const [name, token] of Object.entries(before)) {
      if (!(name in after)) {
        entries.push({ kind: 'removed', group, name, mode: null, before: token.$value, after: undefined });
      }
    }
  }

  const counts = { added: 0, removed: 0, changed: 0 };
  for (const entry of entries) counts[entry.kind]++;
  return { entries, counts };
}

/** Human-readable lines, one per change. Mode-scoped changes carry a `[mode]` tag. */
export function formatDiffLines(diff) {
  const label = (entry) => `${entry.group} ${entry.name}${entry.mode ? ` [${entry.mode}]` : ''}`;
  return diff.entries.map((entry) => {
    if (entry.kind === 'added') return `  + ${label(entry)} = ${JSON.stringify(entry.after)}`;
    if (entry.kind === 'removed') return `  - ${label(entry)} (was ${JSON.stringify(entry.before)})`;
    return `  ~ ${label(entry)}: ${JSON.stringify(entry.before)} -> ${JSON.stringify(entry.after)}`;
  });
}

/** `{added: 1, changed: 2, removed: 0}` -> "2 changed, 1 added". Empty string when nothing moved. */
export function summarizeDiff(diff) {
  const parts = [];
  if (diff.counts.changed) parts.push(`${diff.counts.changed} changed`);
  if (diff.counts.added) parts.push(`${diff.counts.added} added`);
  if (diff.counts.removed) parts.push(`${diff.counts.removed} removed`);
  return parts.join(', ');
}

/**
 * Drops the generated-by header so a re-extraction timestamp alone does not
 * read as a change. Used by `generate --check` (the CI drift gate) and by
 * sync's "which files really changed" summary — they must agree, which is why
 * this lives in one place.
 */
export function stripGeneratedHeader(contents) {
  if (contents == null) return null;
  return contents
    .split('\n')
    .filter((line) => !/Source:|Regenerate:|Skill version:|GENERATED BY figma-token-export|extracted \d{4}-/.test(line))
    .join('\n')
    .trim();
}
