// Target: Flutter / Dart.
//
// Emits plain `abstract final class` holders of `static const` values. Const
// matters: it keeps tokens usable in const constructors and const widget
// subtrees, which is where Flutter's rebuild savings actually come from.
// Wiring these into a ThemeExtension is left to the app — see
// references/target-flutter.md.
import { toCamel, toPascal, assertUniqueIdentifiers, avoidReserved } from '../naming.mjs';
import { groupByNamespace } from '../dtcg.mjs';
import { SKILL_VERSION } from '../version.mjs';

function header(target) {
  return `// GENERATED BY figma-token-export — DO NOT EDIT BY HAND.
// Source: ${target.sourceLabel}
// Regenerate: node "$S/sync.mjs" (see this project's README for $S)
// Skill version: figma-token-export ${SKILL_VERSION}
// ignore_for_file: unused_import
`;
}

/** tokens.json stores #RRGGBBAA; Dart's Color wants 0xAARRGGBB. */
function hexToDartColor(hex) {
  const clean = hex.replace('#', '');
  const [rr, gg, bb] = [clean.slice(0, 2), clean.slice(2, 4), clean.slice(4, 6)];
  const aa = clean.slice(6, 8) || 'FF';
  return `0x${aa}${rr}${gg}${bb}`.toUpperCase().replace('0X', '0x');
}

/** Dart needs a literal double: 8 -> 8.0, 1.5 -> 1.5. */
function dartDouble(n) {
  return Number.isInteger(n) ? `${n}.0` : String(n);
}

function fontWeightConst(weight) {
  const rounded = Math.min(900, Math.max(100, Math.round((Number(weight) || 400) / 100) * 100));
  return `FontWeight.w${rounded}`;
}

function classBlock({ className, docLine, fields }) {
  return `${docLine}\nabstract final class ${className} {\n  const ${className}._();\n\n${fields.join('\n\n')}\n}\n`;
}

/** The class declarations for a colour map — no header, so a mode file can reuse them. */
function buildColorClasses(tokens, target) {
  const entries = Object.entries(tokens);
  if (entries.length === 0) return null;

  // Where each colour will live, so an alias can name it across classes.
  const classOfToken = new Map();

  const emitClass = (className, group) => {
    const pairs = Object.entries(group).map(([name]) => [name, toCamel(name)]);
    assertUniqueIdentifiers(pairs, className);
    const fields = pairs.map(([name, id]) => {
      const token = group[name];
      const aliasOf = target.aliasMap?.get(name);
      if (aliasOf) {
        // Referencing the primitive keeps one source of truth: change the
        // palette and every semantic colour built on it follows.
        const aliasClass = classOfToken.get(aliasOf);
        const ref = aliasClass && aliasClass !== className ? `${aliasClass}.${toCamel(aliasOf)}` : toCamel(aliasOf);
        return `  /// Figma: \`${name}\` → \`${aliasOf}\` (${token.$value})\n  static const Color ${id} = ${ref};`;
      }
      return `  /// Figma: \`${name}\` (${token.$value})\n  static const Color ${id} = Color(${hexToDartColor(token.$value)});`;
    });
    return classBlock({ className, docLine: `/// Colour tokens.`, fields });
  };

  // A namespace already named "color" would produce `PPColorColors`.
  const colorClassName = (ns) =>
    /^colou?rs?$/i.test(ns) ? `${target.prefix}Colors` : `${target.prefix}${toPascal(ns)}Colors`;

  let body;
  if (target.groupColorsByNamespace === true) {
    const groups = [...groupByNamespace(tokens)];
    assertUniqueIdentifiers(groups.map(([ns]) => [ns, colorClassName(ns)]), 'colour class names');
    // Populate the token → class index before emitting, so a class can
    // reference a primitive that is declared in a later class.
    for (const [ns, group] of groups) {
      for (const name of Object.keys(group)) classOfToken.set(name, colorClassName(ns));
    }
    body = groups.map(([ns, group]) => emitClass(colorClassName(ns), group)).join('\n');
  } else {
    const className = `${target.prefix}Colors`;
    for (const [name] of entries) classOfToken.set(name, className);
    body = emitClass(className, Object.fromEntries(entries));
  }

  return body;
}

function generateColors(tokens, target) {
  const body = buildColorClasses(tokens, target);
  if (!body) return null;
  return { file: 'colors.g.dart', contents: `${header(target)}\nimport 'dart:ui' show Color;\n\n${body}` };
}

function generateDimensions(tokens, target, reserved) {
  if (Object.keys(tokens).length === 0) return null;

  const blocks = [...groupByNamespace(tokens)].map(([ns, group]) => {
    // `typography/font-size/*` would name its class AppTypography — the same
    // class generateTypography emits, in another file, both exported from
    // tokens.g.dart. Dart rejects that at compile time, so the scale takes the
    // suffix and the text styles keep the plain name.
    const className = avoidReserved(`${target.prefix}${toPascal(ns)}`, reserved);
    // The namespace is already in the class name, so drop it from the field.
    const pairs = Object.entries(group).map(([name]) => [name, toCamel(name, { dropSegments: 1 })]);
    assertUniqueIdentifiers(pairs, className);
    const fields = pairs.map(([name, id]) => {
      const value = group[name].$value;
      return `  /// Figma: \`${name}\`\n  static const double ${id} = ${dartDouble(value)};`;
    });
    return classBlock({ className, docLine: `/// \`${ns}\` scale.`, fields });
  });

  return { file: 'dimensions.g.dart', contents: `${header(target)}\n${blocks.join('\n')}` };
}

function generateTypography(tokens, target) {
  const entries = Object.entries(tokens);
  if (entries.length === 0) return null;

  const className = `${target.prefix}Typography`;
  const pairs = entries.map(([name]) => [name, toCamel(name)]);
  assertUniqueIdentifiers(pairs, className);

  const fields = entries.map(([name, token], i) => {
    const v = token.$value;
    const id = pairs[i][1];
    const args = [];
    const family = target.fontFamily ?? v.fontFamily;
    if (family) args.push(`    fontFamily: '${family}',`);
    if (target.fontPackage) args.push(`    package: '${target.fontPackage}',`);
    if (v.fontSize != null) args.push(`    fontSize: ${dartDouble(v.fontSize)},`);
    args.push(`    fontWeight: ${fontWeightConst(v.fontWeight)},`);
    // Flutter's `height` is a multiplier of fontSize, not a pixel value.
    if (v.lineHeight != null && v.fontSize) {
      args.push(`    height: ${dartDouble(Number((v.lineHeight / v.fontSize).toFixed(4)))},`);
    }
    if (v.letterSpacing) args.push(`    letterSpacing: ${dartDouble(v.letterSpacing)},`);

    const doc = `  /// Figma: \`${name}\`${v.lineHeight != null && v.fontSize ? ` — ${v.fontSize}/${v.lineHeight}px` : ''}`;
    return `${doc}\n  static const TextStyle ${id} = TextStyle(\n${args.join('\n')}\n  );`;
  });

  return {
    file: 'typography.g.dart',
    contents: `${header(target)}\nimport 'package:flutter/painting.dart' show TextStyle, FontWeight;\n\n${classBlock({
      className,
      docLine: '/// Typography tokens.',
      fields,
    })}`,
  };
}

/**
 * Shadows become `static const List<BoxShadow>` — the shape `BoxDecoration`,
 * `Material`, and `Container` all take directly.
 *
 * Two deliberate limits:
 *
 *  - Colours are literals, not references to the colour class. `BoxShadow`
 *    needs a `Color`, and a `const` list cannot resolve a cross-class reference
 *    when `groupColorsByNamespace` moves that colour into a different class.
 *    The Figma colour token is named in the doc comment instead.
 *  - Flutter's `BoxShadow` has no inset. A token with an inner-shadow layer is
 *    skipped and named in a comment, because silently dropping the layer would
 *    ship a shadow that does not match the design.
 */
function buildShadowClass(tokens, className) {
  const usable = Object.entries(tokens).filter(([, token]) => !token.$value.some((layer) => layer.inset));
  const skipped = Object.keys(tokens).filter((name) => !usable.some(([n]) => n === name));
  if (usable.length === 0) return { body: null, skipped };

  const pairs = usable.map(([name]) => [name, toCamel(name)]);
  assertUniqueIdentifiers(pairs, className);

  const fields = usable.map(([name, token], i) => {
    const layers = token.$value.map((layer) => {
      const args = [
        `color: Color(${hexToDartColor(layer.color)})`,
        `offset: Offset(${dartDouble(layer.offsetX)}, ${dartDouble(layer.offsetY)})`,
        `blurRadius: ${dartDouble(layer.blur)}`,
        `spreadRadius: ${dartDouble(layer.spread)}`,
      ];
      const from = layer.colorRef ? `  // ${layer.colorRef}` : '';
      return `    BoxShadow(${args.join(', ')}),${from}`;
    });
    return `  /// Figma: \`${name}\`\n  static const List<BoxShadow> ${pairs[i][1]} = [\n${layers.join('\n')}\n  ];`;
  });

  return { body: classBlock({ className, docLine: '/// Shadow tokens.', fields }), skipped };
}

function generateShadows(set, target) {
  const blocks = [];
  const notes = [];

  const base = buildShadowClass(set.shadow ?? {}, `${target.prefix}Shadows`);
  if (base.body) blocks.push(base.body);
  notes.push(...base.skipped.map((name) => `// SKIPPED (inner shadow — Flutter's BoxShadow has no inset): ${name}`));

  for (const { mode, projected } of target.modeBlocks ?? []) {
    const modeClass = buildShadowClass(projected.shadow ?? {}, `${target.prefix}${toPascal(mode)}Shadows`);
    if (modeClass.body) blocks.push(`// ---------- mode: ${mode} ----------\n\n${modeClass.body}`);
  }

  if (!blocks.length) return null;
  return {
    file: 'shadows.g.dart',
    contents:
      `${header(target)}\nimport 'dart:ui' show Color, Offset;\n` +
      `import 'package:flutter/painting.dart' show BoxShadow;\n\n` +
      `${notes.length ? `${notes.join('\n')}\n\n` : ''}${blocks.join('\n')}`,
  };
}

/**
 * A full second colour class per extra mode. Unlike CSS — where an override
 * block cascades — Dart has no cascade, so a partial class would leave the
 * unchanged colours undefined. Each mode class therefore carries every colour,
 * and the app picks a class per theme.
 */
function generateModeColors(target) {
  const blocks = [];
  for (const { mode, projected, aliasMap } of target.modeBlocks ?? []) {
    if (!Object.keys(projected.color ?? {}).length) continue;
    const modeTarget = { ...target, prefix: `${target.prefix}${toPascal(mode)}`, aliasMap };
    const body = buildColorClasses(projected.color, modeTarget);
    if (body) blocks.push({ mode, contents: body });
  }
  if (!blocks.length) return null;
  return {
    file: 'colors_modes.g.dart',
    contents:
      `${header(target)}\nimport 'dart:ui' show Color;\n\n` +
      blocks.map((b) => `// ---------- mode: ${b.mode} ----------\n\n${b.contents}`).join('\n'),
  };
}

export function generateFlutter(set, target) {
  // Class names this run declares outside the dimension namespaces. Every file
  // is re-exported from tokens.g.dart, so two classes of one name anywhere in
  // the set is a compile error in the app.
  const reserved = new Set([`${target.prefix}Colors`]);
  if (Object.keys(set.typography ?? {}).length) reserved.add(`${target.prefix}Typography`);
  if (Object.keys(set.shadow ?? {}).length) reserved.add(`${target.prefix}Shadows`);
  for (const { mode } of target.modeBlocks ?? []) {
    reserved.add(`${target.prefix}${toPascal(mode)}Colors`).add(`${target.prefix}${toPascal(mode)}Shadows`);
  }

  const files = [
    generateColors(set.color, target),
    generateModeColors(target),
    generateDimensions(set.dimension, target, reserved),
    generateTypography(set.typography, target),
    generateShadows(set, target),
  ].filter(Boolean);

  files.push({
    file: 'tokens.g.dart',
    contents: `${header(target)}\n${files.map((f) => `export '${f.file}';`).join('\n')}\n`,
  });

  return files;
}
