// Target: Web — CSS custom properties + a typed TypeScript mirror.
//
// The CSS file is the single source of runtime values; the TS file exposes the
// same tokens as `var(--…)` references plus their literal values. Components
// should reference the vars (themeable at runtime), and reach for the literals
// only where a var cannot go — canvas, inline SVG attributes, JS animations.
import { toCamel, toKebab, assertUniqueIdentifiers, avoidReserved } from '../naming.mjs';
import { groupByNamespace } from '../dtcg.mjs';
import { SKILL_VERSION } from '../version.mjs';

const HEADER_LINES = (target) => [
  'GENERATED BY figma-token-export — DO NOT EDIT BY HAND.',
  `Source: ${target.sourceLabel}`,
  `Skill version: figma-token-export ${SKILL_VERSION}`,
  'Regenerate: node "$S/sync.mjs" (see this project\'s README for $S)',
];

/** CSS gets one block comment; TS gets a line comment per line (a bare
 *  continuation line is valid CSS-adjacent noise but a TS syntax error). */
function header(target, style = 'block') {
  const lines = HEADER_LINES(target);
  return style === 'line'
    ? `${lines.map((l) => `// ${l}`).join('\n')}\n`
    : `/* ${lines.join('\n   ')} */\n`;
}

/** #RRGGBBAA -> #RRGGBB when fully opaque, otherwise a browser-safe rgb()/alpha form. */
function cssColor(hex8) {
  const rgb = hex8.slice(1, 7);
  const alpha = hex8.slice(7, 9).toUpperCase();
  if (alpha === 'FF' || alpha === '') return `#${rgb.toLowerCase()}`;
  const [r, g, b] = [0, 2, 4].map((i) => parseInt(rgb.slice(i, i + 2), 16));
  const a = Number((parseInt(alpha, 16) / 255).toFixed(3));
  return `rgb(${r} ${g} ${b} / ${a})`;
}

function cssLength(value, target) {
  if (value === 0) return '0';
  if (target.dimensionUnit === 'rem') {
    return `${Number((value / (target.remBase ?? 16)).toFixed(4))}rem`;
  }
  if (target.dimensionUnit === 'raw') return String(value);
  return `${value}px`;
}

function varName(name, target) {
  return `--${target.cssPrefix ?? ''}${toKebab(name)}`;
}

/**
 * One box-shadow value from a shadow token's stacked layers.
 *
 * A layer whose colour came from a variable is emitted as `var(--that-token)`
 * when the target actually emits that token — which is the whole point of
 * keeping `colorRef` through extraction: re-theming the shadow colour then
 * re-themes the shadow. When the colour token was filtered out of this target,
 * a var() would dangle, so the literal is used instead.
 *
 * Lengths stay literal even though Figma has them as variables too: they are
 * emitted alongside as `--shadow-radius-md` for anyone who wants them, and a
 * box-shadow built from four nested var() calls is unreadable in devtools.
 */
function cssShadow(token, set, target) {
  return token.$value
    .map((layer) => {
      const color =
        layer.colorRef && set.color?.[layer.colorRef]
          ? `var(${varName(layer.colorRef, target)})`
          : cssColor(layer.color);
      const lengths = [layer.offsetX, layer.offsetY, layer.blur, layer.spread]
        .map((n) => cssLength(n, target))
        .join(' ');
      return `${layer.inset ? 'inset ' : ''}${lengths} ${color}`;
    })
    .join(', ');
}

function generateCss(set, target) {
  const lines = [header(target), `:root {`];

  const section = (title, body) => {
    if (!body.length) return;
    lines.push(`  /* ${title} */`, ...body, '');
  };

  section(
    'Colour',
    Object.entries(set.color).map(([name, token]) => {
      // An aliased token points at the primitive's var, so overriding the
      // primitive in a theme reaches every semantic token built on it —
      // the structure Figma has and a flat literal throws away.
      const aliasOf = target.aliasMap?.get(name);
      const value = aliasOf ? `var(${varName(aliasOf, target)})` : cssColor(token.$value);
      const trailer = aliasOf ? `  /* ${cssColor(token.$value)} */` : '';
      return `  ${varName(name, target)}: ${value};${trailer}`;
    }),
  );

  for (const [ns, group] of groupByNamespace(set.dimension)) {
    section(
      ns,
      Object.entries(group).map(([name, token]) => `  ${varName(name, target)}: ${cssLength(token.$value, target)};`),
    );
  }

  section(
    'Shadow',
    Object.entries(set.shadow ?? {}).map(
      ([name, token]) => `  ${varName(name, target)}: ${cssShadow(token, set, target)};`,
    ),
  );

  const typographyLines = [];
  for (const [name, token] of Object.entries(set.typography)) {
    const v = token.$value;
    const base = varName(name, target);
    if (v.fontFamily) typographyLines.push(`  ${base}-font-family: ${JSON.stringify(v.fontFamily)}, sans-serif;`);
    if (v.fontSize != null) typographyLines.push(`  ${base}-font-size: ${cssLength(v.fontSize, target)};`);
    typographyLines.push(`  ${base}-font-weight: ${v.fontWeight ?? 400};`);
    if (v.lineHeight != null && v.fontSize) {
      typographyLines.push(`  ${base}-line-height: ${Number((v.lineHeight / v.fontSize).toFixed(4))};`);
    }
    if (v.letterSpacing) typographyLines.push(`  ${base}-letter-spacing: ${cssLength(v.letterSpacing, target)};`);
  }
  section('Typography', typographyLines);

  // Trailing blank line from the last section would close the block oddly.
  while (lines.at(-1) === '') lines.pop();
  lines.push('}', '');

  // One block per extra mode, holding ONLY the tokens that actually differ.
  // A theme is an override set: restating the identical tokens would bloat the
  // file and hide which ones the mode really changes.
  for (const { mode, selector, overrides, projected, aliasMap } of target.modeBlocks ?? []) {
    const body = [];
    for (const group of ['color', 'dimension', 'shadow']) {
      // typography is skipped on purpose: it expands to several properties, so
      // an override block would have to restate all of them.
      for (const [name, token] of Object.entries(overrides[group] ?? {})) {
        if (group === 'shadow') {
          body.push(`  ${varName(name, target)}: ${cssShadow(token, projected, target)};`);
          continue;
        }
        const aliasOf = aliasMap?.get(name);
        const value =
          group === 'color'
            ? (aliasOf ? `var(${varName(aliasOf, target)})` : cssColor(token.$value))
            : cssLength(token.$value, target);
        const trailer = aliasOf ? `  /* ${cssColor(token.$value)} */` : '';
        body.push(`  ${varName(name, target)}: ${value};${trailer}`);
      }
    }
    if (!body.length) continue;
    lines.push('', `/* mode: ${mode} */`, `${selector} {`, ...body, '}', '');
  }

  // A shorthand utility class per typography token — the common case is
  // applying a whole text style, not five individual properties.
  const utilities = Object.keys(set.typography).map((name) => {
    const base = varName(name, target);
    return `.${target.cssPrefix ?? ''}${toKebab(name)} {
  font-family: var(${base}-font-family);
  font-size: var(${base}-font-size);
  font-weight: var(${base}-font-weight);
  line-height: var(${base}-line-height);
  letter-spacing: var(${base}-letter-spacing, normal);
}`;
  });
  if (utilities.length && target.typographyClasses !== false) {
    lines.push('', ...utilities, '');
  }

  return { file: 'tokens.css', contents: lines.join('\n') };
}

/** The same shadow with every colour resolved — for the TS literal map, where a var() would not resolve. */
function cssShadowLiteral(token, target) {
  return cssShadow(token, { color: {} }, target);
}

function tsObject(entries, indent = '  ') {
  return entries.map(([key, value]) => `${indent}${key}: ${value},`).join('\n');
}

function generateTs(set, target) {
  const colorPairs = Object.keys(set.color).map((name) => [name, toCamel(name)]);
  assertUniqueIdentifiers(colorPairs, 'color');
  const typographyPairs = Object.keys(set.typography).map((name) => [name, toCamel(name)]);
  assertUniqueIdentifiers(typographyPairs, 'typography');

  const blocks = [];

  // Symbols this file declares that are NOT derived from a namespace. A design
  // system with a `typography/font-size/*` scale would otherwise emit a second
  // `export const typography` next to the text styles — a TS compile error in
  // the consuming project, found long after the export ran.
  const reserved = new Set(['color', 'colorVar']);
  if (Object.keys(set.shadow ?? {}).length) reserved.add('boxShadow').add('boxShadowVar');
  if (typographyPairs.length) reserved.add('typography');

  const dimensionGroups = [...groupByNamespace(set.dimension)].map(([ns, group]) => ({
    ns,
    group,
    objectName: avoidReserved(toCamel(ns), reserved),
  }));
  assertUniqueIdentifiers(
    [
      ...[...reserved].map((name) => [name, name]),
      ...dimensionGroups.map(({ ns, objectName }) => [`dimension namespace "${ns}"`, objectName]),
    ],
    'exported TypeScript const names',
  );

  blocks.push(`/** Literal colour values, \`#rrggbb\` or \`rgb(r g b / a)\`. */
export const color = {
${tsObject(colorPairs.map(([name, id]) => [id, JSON.stringify(cssColor(set.color[name].$value))]))}
} as const;

/** The same colours as \`var(--…)\` references — prefer these in components. */
export const colorVar = {
${tsObject(colorPairs.map(([name, id]) => [id, JSON.stringify(`var(${varName(name, target)})`)]))}
} as const;

export type ColorToken = keyof typeof color;`);

  for (const { ns, group, objectName } of dimensionGroups) {
    const pairs = Object.keys(group).map((name) => [name, toCamel(name, { dropSegments: 1 })]);
    assertUniqueIdentifiers(pairs, ns);
    const typeName = `${objectName.replace(/^./, (c) => c.toUpperCase())}Token`;
    blocks.push(`/** \`${ns}\` scale (numbers are px as authored in Figma). */
export const ${objectName} = {
${tsObject(pairs.map(([name, id]) => [id, String(group[name].$value)]))}
} as const;

export type ${typeName} = keyof typeof ${objectName};`);
  }

  const shadowPairs = Object.keys(set.shadow ?? {}).map((name) => [name, toCamel(name)]);
  if (shadowPairs.length) {
    assertUniqueIdentifiers(shadowPairs, 'shadow');
    // `boxShadow`, not `shadow`: a design system with a `shadow/*` dimension
    // namespace (offsets, radii) already exports `export const shadow`, and two
    // consts of the same name is a compile error rather than a bad name.
    blocks.push(`/** Ready-to-use \`box-shadow\` values. */
export const boxShadow = {
${tsObject(shadowPairs.map(([name, id]) => [id, JSON.stringify(cssShadowLiteral(set.shadow[name], target))]))}
} as const;

/** The same shadows as \`var(--…)\` references — prefer these in components. */
export const boxShadowVar = {
${tsObject(shadowPairs.map(([name, id]) => [id, JSON.stringify(`var(${varName(name, target)})`)]))}
} as const;

export type BoxShadowToken = keyof typeof boxShadow;`);
  }

  if (typographyPairs.length) {
    const entries = typographyPairs.map(([name, id]) => {
      const v = set.typography[name].$value;
      const fields = [
        v.fontFamily ? `fontFamily: ${JSON.stringify(`${v.fontFamily}, sans-serif`)}` : null,
        v.fontSize != null ? `fontSize: ${JSON.stringify(cssLength(v.fontSize, target))}` : null,
        `fontWeight: ${v.fontWeight ?? 400}`,
        v.lineHeight != null && v.fontSize ? `lineHeight: ${Number((v.lineHeight / v.fontSize).toFixed(4))}` : null,
        v.letterSpacing ? `letterSpacing: ${JSON.stringify(cssLength(v.letterSpacing, target))}` : null,
      ].filter(Boolean);
      return [id, `{ ${fields.join(', ')} }`];
    });
    // `satisfies React.CSSProperties` is opt-in: it is a nice guard rail in a
    // React app and a hard compile error everywhere else.
    const constraint = target.react === true ? ` satisfies Record<string, React.CSSProperties>` : '';
    blocks.push(`/** Text styles, shaped for a \`style\` prop or a CSS-in-JS object. */
export const typography = {
${tsObject(entries)}
} as const${constraint};

export type TypographyToken = keyof typeof typography;`);
  }

  const reactImport = typographyPairs.length && target.react === true ? `import type React from 'react';\n\n` : '';
  return { file: 'tokens.ts', contents: `${header(target, 'line')}\n${reactImport}${blocks.join('\n\n')}\n` };
}

export function generateWeb(set, target) {
  return [generateCss(set, target), generateTs(set, target)];
}
